#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.

# Configure HOST
HOST = data.get('host')
agent.set_env('APP_URL', HOST)

rdb = agent.redis_connect(use_replica=True)
smtp_settings = agent.get_smarthost_settings(rdb)
MAIL_DRIVER = "smtp"
MAIL_FROM_ADDRESS = smtp_settings['username']
MAIL_FROM_NAME = "DOCMOST"+"<"+MAIL_FROM_ADDRESS+">"
# SMTP Configuration
## Set the default values
SMTP_HOST=smtp_settings['host']
# OPTIONAL: Defines the port to use for sending emails.
SMTP_PORT=smtp_settings['port']
# OPTIONAL: Defines the username to use with the SMTP server.
SMTP_USERNAME=smtp_settings['username']
# OPTIONAL: Defines the password to use with the SMTP server.
SMTP_PASSWORD=smtp_settings['password']

smtp_config = {
    'MAIL_DRIVER': MAIL_DRIVER,
    'MAIL_FROM_ADDRESS': MAIL_FROM_ADDRESS,
    'MAIL_FROM_NAME': MAIL_FROM_NAME,
    'SMTP_HOST': SMTP_HOST,
    'SMTP_PORT': SMTP_PORT,
    'SMTP_USERNAME': SMTP_USERNAME,
    'SMTP_PASSWORD': SMTP_PASSWORD
}
agent.write_envfile("smtp-config.env",smtp_config)

# just before starting systemd unit
agent.dump_env()
